=== nemanjastev1/Provera-Znanja/magacin.dtd
<!ELEMENT magacin (Artikal+)>
<!ELEMENT Artikal (naziv,datumIzrade+,cena,kompanija+,emailProdavca)>
<!ELEMENT naziv(#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT emailProdavca (#PCDATA)>

<!ELEMENT datumIzrade (dan,mesec,godina+)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>

<!ELEMENT kompanija (ime,adresa)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>

=== nemanjastev1/Provera-Znanja/magacin.xml
<?xml version="1.0"?>
<!DOCTYPE magacin SYSTEM "magacin.dtd">
<magacin>
    <Artikal>
        <naziv sifra="001">Vafl</naziv>
        <datumIzrade>
            <dan>12</dan>
            <mesec>3</mesec>
            <godina>2019</godina>
        </datumIzrade>
        <cena valuta="RSD">20</cena>
        <kompanija>
            <ime>Swisslion</ime>
            <adresa>Takovo BB</adresa>
        </kompanija>
        <emailProdavca>Swisslion@gmail.com</emailProdavca>
    </Artikal>
</magacin>
